# Generated by Django 3.2.5 on 2022-08-08 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacture', models.CharField(choices=[('Kyocera', 'Kyocera'), ('HP', 'HP')], max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacture', models.CharField(choices=[('Kyocera', 'Kyocera'), ('HP', 'HP')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('printers', models.ManyToManyField(blank=True, null=True, related_name='structures', to='main.Printer')),
            ],
        ),
        migrations.CreateModel(
            name='CartridgeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartridges', to='main.cartridge')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartridges', to='main.structure')),
            ],
        ),
        migrations.CreateModel(
            name='CartridgeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_complete', models.DateTimeField()),
                ('user_create', models.CharField(blank=True, max_length=100, null=True)),
                ('user_complete', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.cartridge')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.structure')),
            ],
        ),
        migrations.CreateModel(
            name='CartridgeMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='main.cartridge')),
                ('from_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_movements', to='main.structure')),
                ('to_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_movements', to='main.structure')),
            ],
        ),
        migrations.AddField(
            model_name='cartridge',
            name='printer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartridges', to='main.printer'),
        ),
    ]
